### ISSUE TITLE
Not all past entries in a month are displayed

### ISSUE THREAD

**Issue by stewsmith** [marbemac/dayjot#19]
When looking at the web interface for previous entries (https://dayjot.com/entries) , not all of the entries are displayed. The calendar on the right displays the correct count, but the interface will only display 20 entries. So for a month with 31 entries, the entries prior to the 12th of the month are inaccessible.

**Comment by Slix** [comment]
I have this issue as well. A month in which I have 21 entries only shows 20 of them. The last (earliest) one is omitted. I can only view it via search or browsing to that specific date.

**Comment by marbemac** [comment]
Is infinite scroll working for you guys? When you scroll to the bottom of the page it should load 20 more. That said, I can certainly up the per page limit to 30-40 or so.

**Comment by stewsmith** [comment]
Infinite scroll works but only up to 20. For users that have written
everyday in a month, they can't view their last ~10 entries. Raising the
per page limit to > 30 should solve this.

**Comment by marbemac** [comment]
Hmm, I'm not sure I follow. When the page loads (haven't scrolled yet) it should load the first 20 posts. When you scroll to the bottom of the page, it *should* load and append the next 20 posts, and so on as you scroll down. Does it work like this for you?

**Comment by stewsmith** [comment]
Uploading a video now.

**Comment by stewsmith** [comment]
http://cl.ly/image/2r2O2k3D3d1P

I can't see entries earlier than March 9th, even though they exist.

**Comment by marbemac** [comment]
Interesting - ok I'll take another look at it tomorrow. Which browser are
you using?

**Comment by stewsmith** [comment]
Chrome 39.0.2171.95

**Comment by marbemac** [comment]
Turned out to be a simple paging issue - should be fixed! Closing for now - let me know if you're still seeing the issue.

ba423d2d6762ae3f8ae065bd77adac38d86fd1cb
