### ISSUE TITLE
CSS has no style for markdown bulleted lists and numbered lists

### ISSUE THREAD

**Issue by Slix** [marbemac/dayjot#20]
Entry view:

![entryview](https://cloud.githubusercontent.com/assets/217986/5698198/c3195594-99cd-11e4-8cbc-deb0732c54fc.png)

Edit view:

![editview](https://cloud.githubusercontent.com/assets/217986/5698201/d88cb83a-99cd-11e4-932a-c37cedf76324.png)

The markdown processor is properly outputting `<ul>` tags and such, so it seems like the problem is just that there's no CSS styling.

**Comment by marbemac** [comment]
All set - 43e5f42c99a9c622508d61be760a170b26514bda
